### PR TITLE
Automatically detect and enable fips

### PR DESCRIPTION
**Pull request by jarretlavallee**
Prior to this commit, this repo did not handle FIPS masters. This commit
enables the detection of FIPS and downloads the correct package. This
commit makes it automatic, so a FIPS master will always get a FIPS
install.

### CODE REVIEW

**Comment by jarretlavallee** [comment]
https://puppet.com/docs/pe/2019.2/fips_compliance.html

https://www.dogtagpki.org/wiki/Configuring_FIPS_on_RHEL

To test this:

1. Create a new machine without the`pe_master` role
2. Enable FIPS
3. Add the `pe_master` role and run `vagrant provision machinename`
4. Verify the installation was successful
5. Verify the installation uses the FIPS package
6. Try to install FIPS agents

**Comment by jarretlavallee** [comment]
@henrywangpuppet ^^

**Comment by huiyuwang10** [comment]
1. Create a new machine without thepe_master role
2. Enable FIPS
3. Add the pe_master role and run vagrant provision machinename - get error message
```
Create a new machine without thepe_master role
==> pe-201911-master-bolt:           "message": "Error downloading PE tarball: http://pe-releases.puppetlabs.lan//2019.1.1/puppet-enterprise-2019.1.1-redhatfips-7-x86_64.tar.gz"
```
I just checked the tarball is not there. Who can help to upload?

**Comment by henrywangpuppet** [comment]
> enterprise

This is me - Henry

**Comment by jarretlavallee** [comment]
@henrywangpuppet FIPS is only enabled in 2019.2.x+ Good catch on this as I will go ahead and gate it

**Comment by jarretlavallee** [comment]
A new commit to handle that has been pushed.

**Comment by henrywangpuppet** [comment]
Have tried multiple times but failed at "provision" step:
1. Provision a VM without pe_master role
2. Enable Fips by: 
https://www.thegeekdiary.com/how-to-make-centos-rhel-7-fips-140-2-compliant/
3. Add the pe_master role and run vagrant provision machinename - hung at 
==> pe-201921-master-bolt: Starting: plan deploy_pe::provision_master
Even enabled debug mode for vagrant doesn't help:

`2019-11-27 12:39 |  INFO | Reading SSH info
==> pe-201818-master: Updating hosts on: pe-201818-master
==> pe-201910-master: Updating hosts on: pe-201910-master
==> pe-201911-agent: Updating hosts on: pe-201911-agent
==> pe-201818-agent: Updating hosts on: pe-201818-agent
==> pe-201921-master-bolt: Running provisioner: deploy_pe::provision_master (bolt)...
2019-11-27 12:40 |  INFO | Reading SSH info
2019-11-27 12:40 |  INFO | Reading SSH info
2019-11-27 12:40 |  INFO | Reading SSH info
2019-11-27 12:40 |  INFO | Reading SSH info
2019-11-27 12:41 |  INFO | Reading SSH info
==> pe-201921-master-bolt: Bolt: Running bolt command locally: /opt/puppetlabs/bin/bolt plan run 'deploy_pe::provision_master' --boltdir '.' --run-as 'root' --params '{"base_url":"http://pe-releases.puppetlabs.lan/","version":"2019.2.1","pe_settings":{"password":"puppetlabs"}}' --inventoryfile '.vagrant/bolt_inventory.yaml' --nodes 'pe-201921-master-bolt'
==> pe-201921-master-bolt: Starting: plan deploy_pe::provision_master
`

**Pull request merged**
